name: Auto Release

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PYTHONUTF8: 1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set environment variables
      run: |
        echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "CURRENT_TIME=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./code/requirements.txt ]; then pip install -r ./code/requirements.txt; fi

    - name: Run GitHub Actions optimized crawler
      run: |
        cd ./code
        echo "开始运行GitHub Actions专用爬虫脚本..."
        python 草榴_P_github_actions.py
        echo "爬虫脚本执行完成"

    - name: Find all created ZIP files
      run: |
        cd ./code
        echo "开始查找创建的ZIP文件..."
        
        # 查找所有zip文件并输出到临时文件
        find . -type f -name "*.zip" > created_zips.txt
        
        # 显示找到的文件数量
        echo "找到 $(wc -l < created_zips.txt) 个ZIP文件"
        
        # 如果没有找到文件，创建一个空文件以避免后续步骤失败
        if [ ! -s created_zips.txt ]; then
            echo "没有找到ZIP文件，创建空文件"
            echo "" > created_zips.txt
        fi
        
        # 显示找到的文件列表（前5个）
        echo "找到的ZIP文件列表："
        head -5 created_zips.txt

    - name: Create GitHub Release and upload assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "每日涩涩-${{ env.CURRENT_DATE }}"
        name: "每日涩涩·${{ env.CURRENT_DATE }}"
        body: "每日涩涩·${{ env.CURRENT_DATE }}\n\n优化内容：\n1. 避免打包空文件夹\n2. 优化大文件和多文件的压缩和上传"
        draft: false
        prerelease: false
        fail_on_unmatched_files: false
        files: |
          ./code/*.zip
          ./code/**/*.zip

    - name: Debug release information
      run: |
        echo "当前目录结构："
        ls -la ./code/
        echo "创建的ZIP文件列表："
        cat ./code/created_zips.txt