name: Auto Release

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v* -每日涩涩-${{ env.CURRENT_DATE }}"
        release_name: "v* -每日涩涩·${{ env.CURRENT_DATE }}"
        body: "v* -每日涩涩·${{ env.CURRENT_DATE }}"
        draft: false
        prerelease: false

    - name: Debug release information
      run: |
        echo "Tag Name: ${{ steps.create_release.outputs.tag_name }}"
        echo "Release ID: ${{ steps.create_release.outputs.id }}"

    - name: Find and upload all zip files in specified directories
      run: |
        # Check if the release was created successfully
        if [ -z "${{ steps.create_release.outputs.tag_name }}" ]; then
          echo "Release creation failed. Exiting..."
          exit 1
        fi

        # Initialize UPLOAD_FILE to an empty string
        UPLOAD_FILE=""

        for dir in "./code/欢迎回家/Archive" "./code/Archive"; do
          find "$dir" -type f -name "*.zip" | while read file; do
            if [ -f "$file" ]; then
              echo "Found $file"
              UPLOAD_FILE="$file"
              echo "UPLOAD_FILE=$file" >> $GITHUB_ENV
              BASENAME=$(basename "$file")
              echo "UPLOAD_FILE_BASENAME=$BASENAME" >> $GITHUB_ENV
            else
              echo "File $file does not exist. Skipping..."
            fi
          done
        done

        # If no zip file was found, set UPLOAD_FILE to an empty string
        if [ -z "$UPLOAD_FILE" ]; then
          echo "UPLOAD_FILE=" >> $GITHUB_ENV
        fi

    - name: Upload zip files to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.UPLOAD_FILE }}
        asset_name: ${{ env.UPLOAD_FILE_BASENAME }}
        asset_content_type: application/zip
      if: env.UPLOAD_FILE != ''