name: Update dailySex

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  clear_folders:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Trigger clear_pic_folder workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: clear_pic_folder
          client-payload: '{"ref": "main"}'
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd code
        python -m pip install --upgrade pip
        pip install chardet fake_useragent
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Runner (Images)
      run: |
        # mkdir -p code/pic
        cd code
        python legacy_scripts/草榴_P_auto.py
    
    - name: Runner (Novels)
      run: |
        # mkdir -p code/欢迎回家/Archive
        cd code
        python legacy_scripts/caoliu_word.py

    - name: Commit changes
      run: |
          git diff
          git config --global user.email 791751568@qq.com
          git config --global user.name adminlove520
          git add code/欢迎回家/Archive/
          git add code/Archive/
          git commit -m "每日涩涩和小说（`date +'%Y-%m-%d'`）"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ github.token }}